"""add API subscription fields

Revision ID: 5f38e2263073
Revises: c232ee863891
Create Date: 2026-03-31 17:03:44.011687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f38e2263073'
down_revision: Union[str, Sequence[str], None] = 'c232ee863891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_plan', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('api_billing_cycle', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('api_subscription_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('api_subscription_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('api_subscription_end_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('api_subscription_end_date')
        batch_op.drop_column('api_subscription_status')
        batch_op.drop_column('api_subscription_id')
        batch_op.drop_column('api_billing_cycle')
        batch_op.drop_column('api_plan')

    # ### end Alembic commands ###
