"""add source to generationhistory

Revision ID: c232ee863891
Revises: 36c81c74fdff
Create Date: 2026-03-30 23:23:40.878654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c232ee863891'
down_revision: Union[str, Sequence[str], None] = '36c81c74fdff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation_history', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
